name: Opam bundle

on:
  pull_request:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
        ocaml-compiler:
          - 4.14.x
          - 5.4.x

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - run: opam install . --deps-only --with-test
      - run: opam exec -- make
      - run: opam exec -- make stub-tests
      - run: opam exec -- make real-tests
        if: matrix.ocaml-compiler == '4.14.x' || matrix.ocaml-compiler == '5.4.x'
